# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  - cmd: Rscript -e "install.packages('remotes'); remotes::install_github('bnosac-dev/tic');"

cache:
- C:\RLibrary

before_build: Rscript -e "tic::before_install()"
build_script: Rscript -e "tic::install()"
after_build: Rscript -e "tic::after_install()"
before_test: Rscript -e "tic::before_script()"
test_script: Rscript -e "tic::script()"
on_success: Rscript -e "try(tic::after_success(), silent = TRUE)"
on_failure: 
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
  - Rscript -e "tic::after_failure()"
before_deploy: Rscript -e "tic::before_deploy()"
deploy_script: Rscript -e "tic::deploy()"
after_deploy: Rscript -e "tic::after_deploy()"
on_finish: Rscript -e "tic::after_script()"

# Adapt as necessary starting from here
environment:
  USE_RTOOLS: true
  R_BUILD_ARGS: --no-manual
  R_CHECK_ARGS: --no-manual
  matrix:
    - R_VERSION: oldrel
    - R_VERSION: stable
    - R_VERSION: release
      R_ARCH: x64
    - R_VERSION: release
      R_ARCH: x64
      GCC_PATH: mingw_64


artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits